livereload: true

# Site settings
title: Kushaiah Felisilda – Filmmaker based in the Philippines
email: krabfx@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
baseurl_blog: "/blog" # the subpath of the blog
url: "test.krabf.com" # the base hostname & protocol for your site, e.g. http://example.com
author: Kushaiah Felisilda
twitter: krabf_
linkedin: kushaiahfelisilda
github:  krabf
instagram: krabf

# Custom Settings
timezone: Asia/Taipei
permalink: /:categories/:title/

# Build settings
markdown: kramdown
incremental: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
include:
  - 404.html